### PR TITLE
Update windows crate to 0.36.0

### PR DESCRIPTION
**Pull request by arnabanimesh**

### CODE REVIEW

**Comment by arnabanimesh** [comment]
@kennykerr Could you check the lack of HWND check i.e. `ok()?` in `src/windows.rs` line no. `84`.

**Comment by kennykerr** [comment]
> @kennykerr Could you check the lack of HWND check i.e. `ok()?` in `src/windows.rs` line no. `84`.

Yes, that's because there is no reliable "invalid" value for `HWND` (the metadata doesn't provide one). In that case, you need to look at the docs for the `CreateWindowExW` function where it states that it returns a 0 value on failure. So if you need to handle that, you'd need to manually check the value of the handle. For example:

```rust
if window.0 == 0 {
    return Err(Error::from_win32());
}
```

cc @riverar who plumbed in this metadata.

**Comment by riverar** [comment]
What's considered invalid for HWNDs changes based on API sadly. Some APIs, for example, consider HWNDs with values `-1`, `0`, and `1` _valid_.

Related upstream metadata PR https://github.com/microsoft/win32metadata/pull/859 FYI

In some future iteration of metadata, we might be able to replace HWND types with more specific types for specific groupings of APIs (e.g. GetXxxWindowHandle, SetXxxWindowHandle can have a XxxWindowHandle rather than a generic HWND). But it's not clear if that's possible or if there's any value there yet. Some research is still required.

**Comment by arnabanimesh** [comment]
Added HWND check handle

**Comment by arnabanimesh** [comment]
@riverar Just so you know, I use `windows-sys` instead of `windows` solely because if I am using `unsafe` why bother with the handle checks, If I have to audit the whole code on my own anyway, I better handle the checks on my own. I can deal with longer compilation times if we can have safe abstractions of WinUI/Win32 API. I don't want impl wrappers and idiomatic rust if there is no added benefit of using Rust in the first place.

**Pull request merged**
