### PR TITLE
Added a build script to support code completion

### PR DESCRIPTION
**Pull request by Josh015**

### CODE REVIEW

**Comment by kennykerr** [comment]
Cargo will do a much better job of caching the results if you used a nested crate. Something like this:

https://github.com/kennykerr/scratch

**Comment by rylev** [comment]
[Note](https://github.com/microsoft/winrt-rs#ide-support): code completion won't work in rust-analyzer when using `include!` unless the "rust-analyzer.cargo.loadOutDirsFromCheck" setting is turned on.

**Comment by Josh015** [comment]
@kennykerr So is that the official recommended way for right now? So far I've just been sticking to small scale changes since I don't know what the project owner has planned.

@rylev Yeah, I saw that in the winrt-rs pull request and wanted to try it out.

**Comment by kennykerr** [comment]
That's up to Robert. I'm just pointing out that this approach isn't going to make the most of Cargo's caching. I'd wait for Robert to chime in, but thanks for your contributions!

**Comment by robmikh** [comment]
I'm all for the subcrate approach, we may as well show off the setup that gives the most benefits. It was on my todo list anyways 🙂

**Comment by kennykerr** [comment]
Here's a description: https://kennykerr.ca/2020/06/08/optimizing-build-with-rust-winrt/ 

The key is putting the code in a separate crate. Next time I'll talk about using a build script to enable code completion, but you can [skip ahead](https://github.com/kennykerr/scratch) if you wish. 😉

**Comment by Josh015** [comment]
There is a slight problem with trying to implement it in the minesweeper example. Namely, the addition of std::ops traits to window

**Comment by Josh015** [comment]
There's a little problem with implementing the bindings crate in the minesweeper-rs project. The custom core::ops traits on Vector* and the From<Duration> on TimeSpan won't compile because of this error:
**"only traits defined in the current crate can be implemented for arbitrary types"**

**Comment by kennykerr** [comment]
Yes, these need to be fixed in winrt-rs itself:

For numerics (Vector2/3): https://github.com/microsoft/winrt-rs/issues/79
For TimeSpan: https://github.com/microsoft/winrt-rs/issues/90

**Comment by Josh015** [comment]
One temporary option would be to move the "numerics.rs" and "time_span.rs" files into the bindings crate since their implementations will eventually come from there anyway. The FromVector2 implementation in "numerics.rs" could be split out and stay in the minesweeper-rs crate.

Thoughts?

**Comment by robmikh** [comment]
That sounds reasonable to me, especially since we'd ideally delete them in the future in favor of the winrt-rs versions.

**Comment by robmikh** [comment]
Looks good to me! Thanks!

**Pull request merged**
